### ISSUE TITLE
duplicate heading

### ISSUE THREAD

**Issue by max397574** [TheCedarPrince/thecedarprince.github.io#13]
![Screenshot 2023-01-03 at 20 27 57](https://user-images.githubusercontent.com/81827001/210427447-2e22c6be-f705-486e-9093-fcb0de9193f8.png)
https://jacobzelko.com/01012023000122-graph-theory-learning/#references

**Comment by TheCedarPrince** [comment]
This has been fixed @max397574 -- thanks for the report on this!
