### ISSUE TITLE
[Feature] Increase Size of Images and Gifs

### ISSUE THREAD

**Issue by TheCedarPrince** [TheCedarPrince/thecedarprince.github.io#23]
I have discovered that for some reason, my website displays images very small! After discussion on the JuliaLang Slack, found a potential fix (or path to a fix) for this:

> Right click on it and select "Inspect" (in Firefox, probably called something else in other browsers). THen you can play around with the CSS and figure out what you need to change. For example, you can remove padding-left and increase width etc
> .franklin-conent img is set to width: 70%
> you could maybe also add another class to those gifs and make those 100% width?
> (oh the franklin-content in line 294 in your franklin.css
> but even with 100% the text font size is a little small, maybe also increase font size in the GIF (reduce lines / number of characters per line)?

Courtesy of: @fredrikekre and @kellertuer

**Comment by kellertuer** [comment]
As a first idea, I used `\floatleftimg{/assets/ronnybergmann.jpg}{R. Bergmann}` [here](https://github.com/kellertuer/kellertuer.github.io/blob/master/index.md), which is the LaTeX variant in Franklin of defining commands, see the definition at https://github.com/kellertuer/kellertuer.github.io/blob/master/config.md (you can also define an `hfun_` instead). That way certain images get some extra code on my page (especially css classes attached and such), which you can style with CSS then.

**Comment by TheCedarPrince** [comment]
So, I actually ended up with a very concise solution that came from your suggestion earlier @kellertuer about:

> .franklin-conent img is set to width: 70%

After some additional tinkering and exploration, there were only a few things I needed to fix namely the following configurations here: https://github.com/TheCedarPrince/thecedarprince.github.io/commit/fea181d33e887f27d10b7aace8593fd3e0a56ea9

Turns out I didn't need to define a Franklin function at all to get a bigger gif or image to show. With that, I have, in my humble opinion (:wink:), an AWESOME looking website now:

![image](https://user-images.githubusercontent.com/29561456/211981200-f5dd7db6-8486-42fa-9afa-9abdbbbfe1eb.png)

Thank you kindly for all the help and have a great day! :100:

**Comment by kellertuer** [comment]
Well, if you just set the width of _all_ images to 100% that is of course also possible, just keep in mind that your profile image on the start page (at least in Safari) is now also 100% in width, that's why it might be a good idea to introduce a semantic class to only change the width (or other styles) for _some_ images.
